# see https://backstage.io/docs/features/software-catalog/descriptor-format/
# and https://backstage.io/docs/features/software-catalog/well-known-annotations/
# and https://backstage.io/docs/features/software-catalog/well-known-relations/
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dotnet-apiserver
  description: A basic API server in .NET
  annotations:
    backstage.io/kubernetes-namespace: dotnet-apiserver
    # this label also determines which Tekton pipeline runs are discovered 
    backstage.io/kubernetes-label-selector: app=dotnet-apiserver
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: dotnet-apiserver
    quay.io/repository-slug: joshgav/dotnet-apiserver
    janus-idp.io/tekton-enabled: 'true'
  links:
    - url: https://blog.joshgav.com/
      title: Josh's blog
      icon: docs
spec:
  type: service
  owner: josh@joshgav.com
  lifecycle: experimental
