apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: dotnet-apiserver
resources:
# - pgdb.yaml
- service.yaml
- instrumentation.yaml
- deployment.yaml
- route.yaml
# - servicemonitor.yaml