apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dotnet-apiserver
spec:
  endpoints:
  - interval: 30s
    port: 80-tcp
    scheme: http
    path: "/healthz"
  selector:
    matchLabels:
      app.kubernetes.io/component: dotnet-apiserver